development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  OAUTH_CALLBACK: 'http://127.0.0.1:3000/access_token'
  ORIGIN: 'http://127.0.0.1:8080/'

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  OAUTH_CALLBACK: 'http://127.0.0.1:3000/access_token'
  ORIGIN: 'http://127.0.0.1:8080/'


# development:
#   secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
#   twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
#   twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
#
# production:
#   secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
#   twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
#   twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
